## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

title = "Ceramika Petra"
theme = "hugo-story"


## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "taxonomyTerm", "section"]
# googleAnalytics = "your-google-analytics-id"


## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]
  description = "A (modular, highly tweakable) responsive one-page theme for Hugo"
  logo = "images/banner.jpg"
  favicon = true

[Params.social]
  github = "/"
  twitter = ""
  email = "biuro@ceramikapetra.pl"
  instagram = "https://instagram.com"
  linkedin = "https://linkedin.com"
  telegram = "https://telegram.org"

  [markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
